### ISSUE TITLE
Upgrade to tokio 0.3

### ISSUE THREAD

**Issue by Jasperav** [WalletConnect/a2#50]
If https://github.com/hyperium/hyper/issues/2352 is finished (and h2 upgraded to tokio 0.3), this library can also be upgraded to tokio 0.3 if I am not mistaking

**Comment by pimeys** [comment]
It's not yet in crates.io! Yeah, will upgrade, and sure hoping we'll be in stable 1.0 tokio soon, so no more need to keep up :)

**Comment by moh-abk** [comment]
Superseded by https://github.com/pimeys/a2/issues/51 @pimeys @Jasperav

**Comment by HarryET** [comment]
Closed because it was superseded and this has been stagnant for over 1 year
