### ISSUE TITLE
API compatibility breakage in new minor version v0.6.2

### ISSUE THREAD

**Issue by losfair** [WalletConnect/a2#58]
In v0.6.2 a new field `url_args` was added to `a2::request::payload::APS` in https://github.com/pimeys/a2/pull/57. This breaks API compatibility: https://github.com/losfair/blueboat/runs/4390068136.

**Comment by HarryET** [comment]
👋🏼  This project now has new maintainers, we see that there was a breaking change with a minor version bump and apologise. Is this issue still pertinent now or can it be closed?

**Comment by HarryET** [comment]
This issue is being closed because it doesn't look like the creator still has the issue.
